### ISSUE TITLE
track users

### ISSUE THREAD

**Issue by anniejw6** [anniejw6/art_flask#17]
Options:
- track anonymously (generate random number with every session?)
- use [Flask Login](https://flask-login.readthedocs.org/en/latest/) - will still need to implement some way of saving anonymous users?

**Comment by anniejw6** [comment]
@jmemich - thoughts?

**Comment by jmemich** [comment]
Login seems to far too formal a requirement. I would have be optional as a preference. We could then associate unique session ids with a common user while still allow people to input data without a login.

**Comment by anniejw6** [comment]
i was thinking a box just pops up asking for an email and password

**Comment by jmemich** [comment]
Sounds good. I'd have it be optional thought.

**Comment by anniejw6** [comment]
Closed via #21
